import { useState } from 'react';
import { Activity, Clock3, Cpu, Leaf, LoaderCircle } from 'lucide-react';
import { Badge, Empty, Metric, Note, Panel, ResourceState } from './components.jsx';
import { METHOD_NAMES } from './lib/api.js';
import { useResource } from './useWorkspace.js';

const ms = (value) => value.toFixed(3);
const percent = (value) => value == null ? '—' : `${(value * 100).toFixed(1)}%`;
const methods = Object.keys(METHOD_NAMES);

export function Algorithms({ run, canCompare, comparing, compareRun, openInput }) {
  const reference = useResource('/benchmarks');
  const [repeats, setRepeats] = useState(5);
  const comparison = run?.comparison;
  const measured = comparison?.methods;
  const maximum = measured ? Math.max(...Object.values(measured).map((item) => item.median_ms)) : 1;
  return <>
    <div className="three-method-cards">{methods.map((method) => <Panel key={method} title={METHOD_NAMES[method]} eyebrow={method === 'exhaustive' ? 'EVERY ELIGIBLE POSITION' : method === 'filtered' ? 'CANONICAL CANDIDATES' : 'ACTUAL ADAPTIVE ROUTING'}><p className="panel-description">{method === 'exhaustive' ? 'Score complete contexts everywhere, then retain canonical GT/AG outputs.' : method === 'filtered' ? 'Scan GT/AG first; apply the shared detailed model only to eligible candidates.' : 'Use the cheap scorer first; call detailed only for uncertain candidates.'}</p><div className="complexity"><span>Fixed model / context</span><strong className="mono">O(n)</strong></div></Panel>)}</div>
    <Panel title="Measure this run" eyebrow={run?.name || 'NO ACTIVE RUN'} action={comparison && <Badge tone="green">Saved comparison</Badge>}>
      {run ? <><p className="panel-description">{run.analysis.input.length.toLocaleString()} bases · same input and settings · warm-up + repeated measurements · saved with this run.</p><div className="selection-controls"><label>Repetitions<select aria-label="Benchmark repetitions" value={repeats} onChange={(event) => setRepeats(Number(event.target.value))}>{[3, 5, 7].map((count) => <option key={count} value={count}>{count} per method</option>)}</select></label><button className="button primary" disabled={!canCompare} onClick={() => compareRun(repeats)}>{comparing ? <LoaderCircle size={17} className="spin" /> : <Clock3 size={17} />}{comparing ? 'Measuring…' : comparison ? 'Measure again' : 'Measure all three methods'}</button></div>{!comparison && <p className="panel-description">Measure to see medians and variation.</p>}</> : <Empty title="Analyse an input first" description="Run an analysis, then return here."><button className="button secondary" onClick={() => openInput('sample')}>Load a real sample</button></Empty>}
    </Panel>
    {comparison && <>
      <div className="metrics-grid"><Metric label="Baseline median" value={ms(measured.exhaustive.median_ms)} unit="ms" detail={`${comparison.repeats} warm trials`} icon={Clock3} /><Metric label="Filtered median" value={ms(measured.filtered.median_ms)} unit="ms" detail={`Runtime reduction ${percent(measured.filtered.runtime_reduction_vs_exhaustive)}`} icon={Cpu} /><Metric label="Adaptive median" value={ms(measured.adaptive.median_ms)} unit="ms" detail={`Runtime reduction ${percent(measured.adaptive.runtime_reduction_vs_exhaustive)}`} icon={Leaf} accent /><Metric label="Detailed work avoided" value={comparison.adaptive_detailed_work_reduction == null ? '—' : (comparison.adaptive_detailed_work_reduction * 100).toFixed(1)} unit="%" detail={`${comparison.adaptive_detailed_evaluations_avoided.toLocaleString()} evaluations vs filtered`} icon={Activity} /></div>
      <Panel title="Measured runtime and estimated energy" action={<Badge tone="green">{comparison.repeats} repetitions</Badge>}>
        <div className="benchmark-chart live-benchmark"><span className="eyebrow">MEDIAN COMPUTATION · MILLISECONDS</span>{methods.map((method) => <div className="benchmark-bar-row" key={method}><span>{METHOD_NAMES[method]}</span><div className="benchmark-track"><span className={method === 'exhaustive' ? 'baseline-fill' : 'optimized-fill'} style={{ width: `${Math.max(2, measured[method].median_ms / maximum * 100)}%` }} /><strong>{ms(measured[method].median_ms)} ms</strong></div></div>)}</div>
        <div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>Method</th><th>Median</th><th>Min–max</th><th>IQR</th><th>Estimated energy</th><th>Estimated reduction</th></tr></thead><tbody>{methods.map((method) => { const value = measured[method]; return <tr key={method}><td>{METHOD_NAMES[method]}</td><td>{ms(value.median_ms)} ms</td><td>{ms(value.min_ms)}–{ms(value.max_ms)} ms</td><td>{ms(value.iqr_ms)} ms</td><td>{value.estimated_joules.toPrecision(4)} J</td><td>{percent(value.estimated_energy_reduction_vs_exhaustive)}</td></tr>; })}</tbody></table></div>
        <Note>Estimated energy = {comparison.energy.assumed_power_watts} W × median seconds. Negative reduction means more energy; at 0 W, reduction is undefined. Power is assumed, not measured.</Note>
      </Panel>
      <Panel title="Actual work and prediction quality"><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>Method</th><th>Scanned positions</th><th>Contexts considered</th><th>Preliminary calls</th><th>Detailed calls</th><th>Changed decisions*</th><th>Donor / acceptor F1</th></tr></thead><tbody>{methods.map((method) => { const value = measured[method]; return <tr key={method}><td>{METHOD_NAMES[method]}</td><td>{value.work.scanned_positions.toLocaleString()}</td><td>{value.work.context_positions_considered.toLocaleString()}</td><td>{value.work.preliminary_evaluations.toLocaleString()}</td><td>{value.work.detailed_evaluations.toLocaleString()}</td><td>{value.prediction_disagreements_vs_exhaustive}</td><td>{value.quality ? `${value.quality.donor.f1.toFixed(3)} / ${value.quality.acceptor.f1.toFixed(3)}` : 'No input labels'}</td></tr>; })}</tbody></table></div><p className="panel-description">*Changes are relative to exhaustive, not accuracy. Baseline/filtered maximum score difference: {comparison.baseline_filtered_max_score_difference}. {measured.adaptive.quality ? 'F1 uses verified annotations, including missed edges; unannotated does not mean inactive.' : 'No upload labels. Validate shows independent test metrics.'}</p></Panel>
      <details className="provenance-details"><summary>Stage timings</summary><Panel title="Stage measurements" eyebrow="MEDIAN PER STAGE"><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>Method</th><th>Input</th><th>Scan</th><th>Context</th><th>Preliminary inference</th><th>Detailed inference</th><th>Other</th></tr></thead><tbody>{methods.map((method) => <tr key={method}><td>{METHOD_NAMES[method]}</td>{['input_ms', 'scan_ms', 'context_ms', 'preliminary_inference_ms', 'detailed_inference_ms', 'other_ms'].map((key) => <td key={key}>{ms(measured[method].median_stages_ms[key])} ms</td>)}</tr>)}</tbody></table></div><p className="panel-description">Inference includes feature encoding. Individual stage medians need not sum to the total median. {comparison.timing_scope}</p></Panel></details>
      <details className="provenance-details"><summary>Comparison hardware and settings</summary><p>{comparison.hardware.os} · {comparison.hardware.cpu} · {comparison.hardware.logical_cpu_count} logical CPUs</p><p>Python {comparison.versions.python} · NumPy {comparison.versions.numpy} · batch {comparison.batch_size} · warm-up {comparison.warmup_runs_per_method} per method · repetitions {comparison.repeats}</p><p className="mono">Model {comparison.model_id}<br />Input SHA-256 {comparison.input.sha256}<br />Saved {new Date(comparison.created_at).toLocaleString()}</p></details>
    </>}
    <details className="provenance-details"><summary>Reference experiments · other inputs</summary><Panel title="Measured reference experiment across inputs" eyebrow="SAVED DEVELOPMENT EXPERIMENT"><ResourceState {...reference} />{reference.data && <><p className="panel-description">A separate {reference.data.benchmark.repeats}-repeat experiment on four real held-out regions and two explicitly synthetic 100,000-base controls. These are recorded measurements on the documented hardware; they are not timings for your current upload. Motif density and length both affect runtime.</p><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>Input</th><th>Bases</th><th>GT/AG density</th><th>Baseline median</th><th>Filtered median</th><th>Adaptive median</th></tr></thead><tbody>{reference.data.benchmark.inputs.map((input) => <tr key={input.id}><td>{input.id}<small className="table-source">{input.split ? 'Real held-out region' : 'Synthetic stress; no truth'}</small></td><td>{input.length.toLocaleString()}</td><td>{percent(input.results.filtered.work.canonical_candidates / (input.length - 1))}</td>{methods.map((method) => <td key={method}>{ms(input.results[method].median_ms)} ms<small className="table-source">IQR {ms(input.results[method].iqr_ms)}</small></td>)}</tr>)}</tbody></table></div><p className="panel-description">{reference.data.benchmark.hardware.cpu} · {reference.data.benchmark.hardware.os} · Python {reference.data.benchmark.versions.python} · NumPy {reference.data.benchmark.versions.numpy}</p><details className="provenance-details"><summary>Reference experiment provenance</summary><p className="mono">Model {reference.data.benchmark.model_id}<br />Artifact SHA-256 {reference.data.artifact_sha256}</p><p>{reference.data.benchmark.timing_scope}</p></details></>}</Panel></details>
    <Note>All methods are O(n). Fewer expensive calls can save time; speedups depend on the input.</Note>
  </>;
}
