import { ArrowRight, Download } from 'lucide-react';
import { Note, Panel } from './components.jsx';
import { sampleFastaUrl } from './lib/api.js';

export function Guide({ openInput, setView, run }) {
  const steps = [
    { title: 'Load DNA', text: 'Try a real sample, paste DNA, or upload one FASTA record.', action: () => openInput('sample'), button: 'Load sequence' },
    { title: 'Analyse', text: 'Choose a method and run name, then Run analysis. Results save automatically.', action: () => setView('analysis'), button: 'Open Analyse' },
    { title: 'Compare', text: 'Measure all three methods on the saved input. Start with 3 repetitions.', action: () => setView('algorithms'), button: 'Open Compare', disabled: !run },
    { title: 'Export', text: 'Download CSV or JSON, print a report, or reopen history.', action: () => setView('reports'), button: 'Open Reports' },
  ];
  return <>
    <Panel title="Start here" className="quick-start-panel"><div className="quick-start-grid">{steps.map((step, index) => <div className="quick-start-step" key={step.title}><span className="reading-number">{index + 1}</span><h3>{step.title}</h3><p>{step.text}</p><button className="button secondary small" disabled={step.disabled} onClick={step.action}>{step.button}<ArrowRight size={14} /></button></div>)}</div><a className="sample-download" href={sampleFastaUrl()} download><Download size={16} />Download test FASTA · ARVCF · 2,402 bases</a><p className="small-muted">Upload this file to test predictions. Choose the built-in ARVCF sample to include annotation checks.</p></Panel>
    <Note>Possible boundaries, not complete introns. Model scores are not calibrated probabilities. Uploaded DNA has no accuracy labels; energy is estimated.</Note>
    <details className="provenance-details"><summary>Input, direction & positions</summary><dl className="glossary"><div><dt>Input</dt><dd>A/C/G/T/N; 20 called bases minimum, 100,000 bases maximum. One FASTA record, header first; files up to 1 MB.</dd></div><div><dt>Direction</dt><dd>DNA is analysed as supplied. No automatic reverse-complement scan. Bundled minus-strand samples are already oriented.</dd></div><div><dt>Position</dt><dd>One-based start of the GT or AG motif within your input, not a genomic coordinate.</dd></div><div><dt>Context</dt><dd>50 bases + two-base motif + 50 bases. Incomplete or N-containing contexts stay unscored, with a reason.</dd></div><div><dt>Filters</dt><dd>Change visible/exported rows. Saved predictions and measurement settings stay fixed.</dd></div></dl></details>
    <details className="provenance-details"><summary>Splicing & the three methods</summary><p>Cells remove introns from RNA and join retained exons. GT donors and AG acceptors are common boundary motifs in DNA; most occurrences are not splice sites.</p><dl className="glossary"><div><dt>Exhaustive</dt><dd>Score every eligible position, then retain canonical GT/AG output.</dd></div><div><dt>Candidate filtering</dt><dd>Find GT/AG first. Score only eligible candidates with the same detailed model; canonical results agree with exhaustive.</dd></div><div><dt>Adaptive</dt><dd>A cheap scorer handles decisive candidates. Uncertain candidates call the detailed model. Compare shows work avoided and any prediction changes.</dd></div></dl><p>All three are O(n) for fixed context/model size. Savings come from fewer expensive evaluations. Speedups depend on the input.</p></details>
    <details className="provenance-details"><summary>Data, scores & evaluation</summary><p>GENCODE v49 / GRCh38 chromosome 22; related and overlapping genes are kept apart across train, validation and test. Thresholds and routing were selected on validation.</p><p>Detailed test F1: donor 0.799, acceptor 0.717. Adaptive: 0.786 / 0.724, avoiding 80.77% of detailed work. Adaptive donor quality fell beyond its validation tolerance. Validate shows the full results.</p><p>Sampled, single-chromosome evaluation limits generalisation. An absent annotation does not prove inactivity. Selecting a verified built-in sample supplies its labels; uploading the same DNA does not.</p><a href="https://www.gencodegenes.org/human/release_49.html" target="_blank" rel="noreferrer">GENCODE release 49</a></details>
    <details className="provenance-details"><summary>Measurements, history & local launch</summary><p>Estimated energy (J) = assumed watts × measured seconds. Compare uses warm-up and repeated computations; timing excludes startup, warm-up, HTTP/UI and history writes.</p><p>Runs and DNA stay in SQLite on this laptop. Reports can rename, reopen or delete them. Downloads remain separate. Stop waiting ignores a pending response; work already started may still save.</p><p>Double-click <code>start-ecosplice.cmd</code>, then open <code>http://127.0.0.1:8765</code>. Normal use needs no internet or retraining.</p><p>Variant effects, cryptic sites, quantization, hardware acceleration, cloud offloading and federated learning remain future work.</p></details>
  </>;
}
