import { useState } from 'react';
import { Activity, CheckCheck, Target } from 'lucide-react';
import { Badge, Metric, Note, Panel, ResourceState } from './components.jsx';
import { useResource } from './useWorkspace.js';

const percentage = (value) => `${(value * 100).toFixed(1)}%`;

function ConfusionMatrix({ metrics }) {
  return <div className="matrix-wrap"><div className="matrix-axis">Predicted result</div><div className="matrix-column-labels"><span>Positive</span><span>Negative</span></div><div className="matrix-with-label"><span className="matrix-row-label">Annotated positive</span><div className="matrix-cell correct"><strong>{metrics.tp.toLocaleString()}</strong><span>True positive</span></div><div className="matrix-cell incorrect"><strong>{metrics.fn.toLocaleString()}</strong><span>False negative</span></div><span className="matrix-row-label">Unannotated negative</span><div className="matrix-cell incorrect"><strong>{metrics.fp.toLocaleString()}</strong><span>False positive</span></div><div className="matrix-cell correct"><strong>{metrics.tn.toLocaleString()}</strong><span>True negative</span></div></div></div>;
}

function Curve({ points, active }) {
  const line = (field) => points.map((point) => `${40 + point.threshold * 620},${170 - point[field] * 140}`).join(' ');
  return <div className="evaluation-curve"><svg viewBox="0 0 710 205" role="img" aria-label="Precision and recall across held-out score thresholds">
    {[0, .5, 1].map((value) => <g key={value}><line x1="40" x2="660" y1={170 - value * 140} y2={170 - value * 140} stroke="#dce7df" /><text x="30" y={174 - value * 140} textAnchor="end" className="axis-label">{value}</text></g>)}
    <polyline points={line('precision')} fill="none" stroke="#287960" strokeWidth="3" /><polyline points={line('recall')} fill="none" stroke="#8a6ba8" strokeWidth="3" />
    <line x1={40 + active.threshold * 620} x2={40 + active.threshold * 620} y1="25" y2="170" stroke="#58705b" strokeDasharray="4 4" />
    {[0, .25, .5, .75, 1].map((value) => <text key={value} x={40 + value * 620} y="193" textAnchor="middle" className="axis-label">{value}</text>)}
  </svg><div className="chart-legend"><span><i className="legend-dot donor" />Precision</span><span><i className="legend-dot acceptor" />Recall</span><span>Model score threshold</span></div></div>;
}

export function Accuracy({ run }) {
  const resource = useResource('/evaluation');
  const [kind, setKind] = useState('donor');
  const [scorer, setScorer] = useState('detailed');
  const [curveIndex, setCurveIndex] = useState(40);
  const evaluation = resource.data?.evaluation;
  if (!evaluation) return <ResourceState {...resource} />;
  const metrics = evaluation.test[scorer][kind].canonical_candidates;
  const curves = evaluation.test_threshold_curves[scorer]?.[kind];
  const curve = curves?.[Math.min(curveIndex, curves.length - 1)];
  const counts = evaluation.test.class_counts;
  const adaptiveWork = Object.values(evaluation.test.adaptive).map((value) => value.routes).filter(Boolean);
  const fast = adaptiveWork.reduce((sum, routes) => sum + routes.preliminary_final, 0);
  const total = adaptiveWork.reduce((sum, routes) => sum + routes.preliminary_final + routes.detailed_final, 0);
  return <>
    <Note>GENCODE v49 / GRCh38 chr22 held-out test data. These metrics describe the model; uploads have no accuracy labels.</Note>
    <div className="selection-controls"><label>Site type<select aria-label="Evaluation site type" value={kind} onChange={(event) => setKind(event.target.value)}><option value="donor">Donor · GT</option><option value="acceptor">Acceptor · AG</option></select></label><label>Scorer / method<select aria-label="Evaluation scorer" value={scorer} onChange={(event) => setScorer(event.target.value)}><option value="detailed">Detailed · exhaustive / filtered</option><option value="adaptive">Adaptive · actual final scorers</option><option value="preliminary">Preliminary reference</option></select></label><Badge tone="green">Frozen validation choices</Badge></div>
    <div className="metrics-grid"><Metric label="Precision" value={(metrics.precision * 100).toFixed(1)} unit="%" detail="Correct / predicted positive" icon={Target} /><Metric label="Recall" value={(metrics.recall * 100).toFixed(1)} unit="%" detail="Found / annotated positive" icon={Target} /><Metric label="F1 score" value={metrics.f1.toFixed(3)} unit="" detail="Balances precision and recall" icon={Activity} accent /><Metric label="Accuracy" value={(metrics.accuracy * 100).toFixed(1)} unit="%" detail={`${metrics.count.toLocaleString()} canonical candidates`} icon={CheckCheck} /></div>
    <div className="two-column"><Panel title="Held-out confusion matrix" eyebrow={`${kind.toUpperCase()} · CANONICAL CANDIDATES`}><ConfusionMatrix metrics={metrics} /></Panel><Panel title="Dataset and decision settings"><div className="provenance-grid"><div><span>Test windows</span><strong>{Object.values(counts).reduce((sum, count) => sum + count, 0).toLocaleString()}</strong></div><div><span>Donor / acceptor / non-site</span><strong>{counts.donor.toLocaleString()} / {counts.acceptor.toLocaleString()} / {counts.non_site.toLocaleString()}</strong></div><div><span>Positive support in this matrix</span><strong>{metrics.support.toLocaleString()} {kind}s</strong></div><div><span>Detailed donor / acceptor threshold</span><strong>{evaluation.thresholds.detailed.donor.toFixed(2)} / {evaluation.thresholds.detailed.acceptor.toFixed(2)}</strong></div><div><span>Preliminary donor / acceptor threshold</span><strong>{evaluation.thresholds.preliminary.donor.toFixed(2)} / {evaluation.thresholds.preliminary.acceptor.toFixed(2)}</strong></div><div><span>Split isolation</span><strong>Overlapping gene groups separated; duplicate contexts removed</strong></div></div><p className="panel-description">Thresholds and routing were selected on validation, before test evaluation. Sampled class balance and one-chromosome scope limit generalisation. Zero is shown for a metric with a zero denominator.</p></Panel></div>
    <details className="provenance-details"><summary>Explore score thresholds</summary>{curves ? <Panel title="Threshold trade-off" eyebrow="DESCRIPTIVE SCENARIO"><Note>Explore saved test results. The slider does not change predictions.</Note><div className="threshold-control"><div><strong>{scorer} {kind} score threshold</strong><span>Scenario {curve.threshold.toFixed(2)} · precision {percentage(curve.precision)} · recall {percentage(curve.recall)}</span></div><input type="range" aria-label="Held-out threshold scenario" min="0" max={curves.length - 1} step="1" value={Math.min(curveIndex, curves.length - 1)} onChange={(event) => setCurveIndex(Number(event.target.value))} /><span className="range-value mono">{curve.threshold.toFixed(2)}</span></div><Curve points={curves} active={curve} /><div className="curve-summary">TP {curve.tp} · FP {curve.fp} · FN {curve.fn} · TN {curve.tn} · F1 {curve.f1.toFixed(3)}</div></Panel> : <Note>Adaptive routing uses frozen scorer-specific thresholds. A single threshold slider cannot describe its two-scorer policy; inspect the detailed or preliminary reference curve.</Note>}</details>
    <Panel title="Adaptive quality and work trade-off"><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>Method</th><th>Donor F1</th><th>Acceptor F1</th><th>Detailed work avoided</th></tr></thead><tbody>{['detailed', 'adaptive', 'preliminary'].map((name) => <tr key={name}><td>{name}</td><td>{evaluation.test[name].donor.canonical_candidates.f1.toFixed(4)}</td><td>{evaluation.test[name].acceptor.canonical_candidates.f1.toFixed(4)}</td><td>{name === 'adaptive' ? `${percentage(fast / total)} (${fast.toLocaleString()} / ${total.toLocaleString()})` : name === 'detailed' ? 'Reference' : 'Cheap scorer reference'}</td></tr>)}</tbody></table></div><p className="panel-description">Adaptive donor test F1 falls more than its validation selection tolerance. This outcome is reported without retuning on test data. Softmax scores are not calibrated biological probabilities.</p></Panel>
    <Panel title="Active input annotation check" eyebrow={run?.name || 'NO ACTIVE RUN'}>{run?.evaluation ? <><p className="panel-description">Separate from population test metrics: this saved input has verified bundled annotations. Unscored annotated edges count as missed sites; absent annotations mean unannotated, not proven inactive.</p><div className="comparison-table-wrap"><table className="comparison-table"><thead><tr><th>Type</th><th>TP / FP / FN / TN</th><th>Precision</th><th>Recall</th><th>F1</th></tr></thead><tbody>{['donor', 'acceptor'].map((type) => <tr key={type}><td>{type}</td><td>{['tp', 'fp', 'fn', 'tn'].map((key) => run.evaluation[type][key]).join(' / ')}</td><td>{percentage(run.evaluation[type].precision)}</td><td>{percentage(run.evaluation[type].recall)}</td><td>{run.evaluation[type].f1.toFixed(3)}</td></tr>)}</tbody></table></div></> : <p className="panel-description">{run ? 'This input has no accompanying ground-truth labels. Its accuracy cannot be calculated.' : 'Analyse a verified sample to see its input-specific annotation check.'}</p>}{run && run.analysis.model_id !== evaluation.model_id && <Note>The active saved run used a different model. Population metrics above belong to {evaluation.model_id}; the run retains its original model identity.</Note>}</Panel>
    <details className="provenance-details"><summary>Evaluation provenance</summary><p className="mono">Model: {evaluation.model_id}<br />Dataset: {evaluation.dataset_fingerprint}<br />Evaluation artifact SHA-256: {resource.data.artifact_sha256}</p><p>{evaluation.test_access_policy}</p></details>
  </>;
}
